#!/bin/sh
rm /usr/bin/e-imzo
rm /etc/xdg/autostart/e-imzo-autorun.desktop
rm /usr/share/applications/e-imzo.desktop
rm /etc/ssl/certs/E-IMZO.pem
rm /usr/local/share/ca-certificates/E-IMZO.crt
update-ca-certificates